### PR TITLE
More cleanup and prettyfying 

### PR DESCRIPTION
**Pull request by palday**
I've already pushed these changes to the published site, but can roll them back if desired.

### CODE REVIEW

**Comment by dmbates** [comment]
@palday Should we mention the Tidier.jl package in the useful packages section?

**Comment by palday** [comment]
> @palday Should we mention the Tidier.jl package in the useful packages section?

@dmbates done

**Comment by dmbates** [comment]
The code for definition and use of the ridgeplot in arrow.qmd is wrapped in `#| eval: false`.  Do we need it?

**Comment by palday** [comment]
Good question -- I think that's one for @kliegl. We can leave it in for now for the next round of revision.

**Comment by kliegl** [comment]
> Good question -- I think that's one for @kliegl. We can leave it in for now for the next round of revision.

@palday @dmbates Actually, not. This is Doug's script - I forgot the purpose of the graphics here. In the same file I noticed a sentence referring to JK's code presented on Monday of SMLP2021. Shall we point to the file -- if still around -- or delete the sentence?

**Comment by palday** [comment]
in that case, I leave the call to you, @dmbates :smile:

**Comment by kliegl** [comment]
Fine with me.  I suspect I had pirated your script, @dmbates,  to try out the MixedModelsMakie function and you were considerate enough not to delete it later.  Good for `git blame`.

**Review by dmbates — APPROVED** [review]

**Pull request merged**
